version: '3'
services:
   web:
     image: portfolio_website
     build: .
     container_name: eliud-portfolio
     restart: always
     ports:
       - "8080:80"  
     volumes: 
      - .:/usr/share/nginx/html